spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-2.cz1y4y4nlexr.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=scheduler
    username: postgres
    password: password
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: super-secret-salt-dev
